# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on: push

permissions:
  contents: read

jobs:
  # run_tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: '3.8'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install pytest
  #   - name: Install package
  #     run: |
  #       pip install .
  #   - name: Unit tests
  #     run: |
  #       python -m pytest tests/
  #       rm -rf tmp/

  deploy:
    needs: run_tests
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        pip install poetry
    - name: Build package
      run: |
        rm -rf dist/
        ls
        ls ../
        poetry build
    - name: pypi-publish
      # You may pin to the exact commit or the version.
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # PyPI user
        user: __token__
        # Password for your PyPI user or an access token
        password: ${{ secrets.PYPI_API_TOKEN }}
        # The repository URL to use
        repository_url: https://github.com/utiasDSL/gym-pybullet-drones
